apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderboard
  labels:
    app: orderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderboard
  template:
    metadata:
      labels:
        app: orderboard
    spec:
      containers:
        - name: orderboard
          image: username/orderboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5